apiVersion: v1
kind: Service
metadata:
  labels:
    app: nest-habit
  name: nest-habit
spec:
  ports:
  - nodePort: 32643
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nest-habit
  type: NodePort
