apiVersion: v1
kind: Service
metadata:
  labels:
    app: nest-habit
  name: nest-habit
spec:
  ports:
  - port: 3200
    protocol: TCP
    targetPort: 3000
  selector:
    app: nest-habit
  type: ClusterIP
